### ISSUE TITLE
Unsupported HTML5 video codecs

### ISSUE THREAD

**Issue by Jingga69** [Tiktodz/android_kernel_asus_sdm660#1]
I find bug in your latest kernel that can't play videos in browser,it say unsuported or error

**Comment by Tiktodz** [comment]
> I find bug in your latest kernel that can't play videos in browser,it say unsuported or error

I didn't find that problem, do you have a log?

**Comment by Jingga69** [comment]
Here the log,i don't know the culprit yet ,the videos in browser just loading and totaly stop,can't even play

[Log_2024-03-08_01-35-35.txt](https://github.com/Tiktodz/android_kernel_asus_sdm660/files/14528642/Log_2024-03-08_01-35-35.txt)

**Comment by Jingga69** [comment]
> > I find bug in your latest kernel that can't play videos in browser,it say unsuported or error
> 
> I didn't find that problem, do you have a log?

Im searching again thoroughly,and i find the issue is unsupported web player video base on html5 format,i hope this help
